### ISSUE TITLE
Analytic CRPS formulas tracking issue

### ISSUE THREAD

**Issue by frazane** [frazane/scoringrules#13]
Issue to track implementation of analytical CRPS formulas, as implemented in [scoringRules](https://cran.r-project.org/web/packages/scoringRules/index.html). 

- [x] beta (`betainc` missing in torch)
- [x] binomial (`betainc` missing in torch)
- [x] exponential
- [x] exponential point mass variant
- [x] gamma 
- [x] gen. extreme value (`expi` missing in torch)
- [x] gen. Pareto
- [x] hypergeometric
- [x] Laplace
- [x] log-Laplace
- [x] log-logistic
- [x] log-normal
- [x] logistic
- [x] logistic truncated
- [x] logistic censored
- [x] logistic point mass variant
- [x] mixture of normals (Ready for PR)
- [x] negative binomial (`hypergeometric` missing in jax, tensorflow and torch)
- [x] normal
- [x] normal truncated
- [x] normal censored
- [x] normal point mass variant
- [x] Poisson
- [x] Student’s t (`hypergeometric` missing in jax, tensorflow and torch)
- [x] Student’s t truncated (`hypergeometric` missing in jax, tensorflow and torch)
- [x] Student's t censored (`hypergeometric` missing in jax, tensorflow and torch)
- [x] Student's t point mass variant (`hypergeometric` missing in jax, tensorflow and torch)
- [x] two-piece exponential
- [x] two-piece normal
- [x] uniform

Notes:
- gamma, beta and bessel functions not supported in numba (affects beta, gamma, gev, poisson, t, generalised t, negative binomial, binomial, hypergeometric, and log-logistic distribution).
- regularised incomplete beta function not supported in torch (affects beta, log-logistic, binomial, hypergeometric, negative binomial, and generalised t distribution)
- hypergeometric function not supported in torch or tensorflow (affects t and negative binomial distribution)
- exponential integral not supported in torch (affects gev distribution)
- hypergeometric cdf needed

**Comment by frazane** [comment]
Closing as complete! 🚀
