### ISSUE TITLE
Analytical log score tracking issue

### ISSUE THREAD

**Issue by sallen12** [frazane/scoringrules#60]
Issue to track implementation of analytical log score formulas:

- [x] beta
- [x] binomial
- [x] exponential
- [x] exponential with loc-scale shift
- [x] gamma
- [x] gen. extreme value
- [x] gen. Pareto
- [x] hypergeometric
- [x] Laplace
- [x] log-Laplace
- [x] log-logistic
- [x] log-normal
- [x] logistic
- [x] logistic truncated
- [x] mixture of normal
- [x] negative binomial
- [x] normal
- [x] normal truncated
- [x] Poisson
- [x] Student’s t
- [x] Student’s t truncated
- [x] two-piece exponential
- [x] two-piece normal
- [x] uniform

**Comment by frazane** [comment]
Closing as complete, big thanks to @sallen12
