### ISSUE TITLE
v1.0.0 tracking issue

### ISSUE THREAD

**Issue by sallen12** [frazane/scoringrules#67]
The scoringRules package in R currently has the following functionality:

- [x] CRPS for ensemble forecasts
- [x] CRPS for parametric distributions
- [ ] LogS for ensemble forecasts (via kernel density estimation)
- [x] LogS for parametric distributions
- [x] Energy score for ensemble forecasts
- [x] Variogram score for ensemble forecasts
- [ ] Gaussian kernel score for ensemble forecasts
- [ ] David-Sebastiani score
- [x] Error-Spread score
- [x] Weighted CRPS for ensemble forecasts
- [ ] Conditional and censored likelihood scores for ensemble forecasts (via kde)
- [x] Weighted Energy score for ensemble forecasts
- [x] Weighted Variogram score for ensemble forecasts
- [ ] Weighted Gaussian kernel score for ensemble forecasts
- [ ] (Discrete) Ranked probability score (RPS)
- [ ] Quantile score
- [x] Interval score

scoringrules (in python) additionally has:
- Brier score (special case of the RPS)
- Weighted interval score
